on:
    pull_request_target:
        types: [ opened, edited ]
jobs:
    label:
        name: conventional-release-labels
        runs-on: ubuntu-latest
        steps:
        - uses: bcoe/conventional-release-labels@v1