name: Initial Setup of Repository

on:
  create:

concurrency:
  group: init-setup
  cancel-in-progress: true

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  init-setup:
    if: github.run_number == 1 && github.event.repository.name != 'plentyshop-pwa'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove unused files
        run: |
          rm -f .github/CODEOWNERS
          rm -f .dockerignore
          rm -f .github/workflows/initial-setup.yaml

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: initial setup of repository"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

