on:
  pull_request:
    types: [review_requested]
jobs:
    notify:
        if: github.actor != 'plenty-cicd-2'
        runs-on: ubuntu-latest
        steps:
          - name: Push release notification
            run: |
              curl --location --request POST '${{ secrets.CHAT_WEBHOOK }}' \
              --header 'Content-Type: application/json' \
              --data-raw '{
                "cardsV2": [
                    {
                        "cardId": "${{ github.event.pull_request.id }}",
                        "card": {
                            "header": {
                                "title": "Boilerplate Review Required",
                                "subtitle": "${{ github.event.pull_request.title }}"
                            },
                            "sections": [
                                {
                                    "widgets": [
                                        {
                                            "buttonList": {
                                                "buttons": {
                                                    "text": "Open PR",
                                                    "onClick": {
                                                        "openLink": {
                                                            "url": "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                ]}'
    